### ISSUE TITLE
tensors is empty when use part_base_engine _feature_extraction

### ISSUE THREAD

**Issue by MinhLe2512** [VlSomers/bpbreid#10]
So I had this error :
TimeoutError:
[WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond    

when trying to run this script :"python scripts/main.py --config-file configs/bpbreid/bpbreid_market1501_test.yaml". And I tried to fix it by downloading the dataset from drive and set the directories as in your instruction
![image](https://user-images.githubusercontent.com/63902542/230849519-67161802-7493-4f57-9901-efd6dff2c073.png)
After that, everything runs just fine until it comes to _feature_extraction at part_based_engine.py and I'm not sure if data_loader is null or not(I'm totally new to Python) but the for loop isn't running at all. 
"RuntimeError: torch.cat(): expected a non-empty list of Tensors". 
I would appreciate if you could guide me a little bit.

**Comment by VlSomers** [comment]
Hi, are all you directory non empty? I guess this happen because the "data_loader" in "_feature_extraction" is empty (can you verify that?). Can you check in "torchreid/data/datasets/image/market1501.py", where the dataset is loaded, if "train", "query" and "gallery" in "__init__" are non empty?

**Comment by MinhLe2512** [comment]
Yes all the are non empty 
![image](https://user-images.githubusercontent.com/63902542/230866707-7ef7a2f9-a978-4db2-8e75-a363c877692b.png).
But apparently the train query and gallery is empty 
![image](https://user-images.githubusercontent.com/63902542/230867725-2d853075-3893-46ea-abec-c0e0890bcea3.png)

**Comment by VlSomers** [comment]
Then there's an issue with you path specification, can you check if self.train_dir, self.query_dir, self.galery_dir match your directory path on disk?

**Comment by MinhLe2512** [comment]
Well they match but instead of having only one '\' the dir has 2 is it wrong or it's just how path works in python
 
F:\ReID\bpbreid\reid-data\Market-1501-v15.09.15\bounding_box_test
![image](https://user-images.githubusercontent.com/63902542/230868803-8c5e3ad2-7889-4ffa-9ed1-6f373d6f098c.png)

**Comment by VlSomers** [comment]
I'm not sure what's happening if the path is correct, I'm sorry, but at least you found the root cause for the error: now you should figure out why the dataset is not located properly (it should definitely be an issue with your path or Windows related stuff)

**Comment by MinhLe2512** [comment]
It's okay thanks for helping me.

**Comment by MinhLe2512** [comment]
Okay so I think I found the problem, apparently the function is trying to get files with .jpg but the dataset contains these instead .npy files, should I reformat it to jpg?

![image](https://user-images.githubusercontent.com/63902542/230895655-fae69608-30cd-45f7-89a4-9d2ce24432c0.png)
![image](https://user-images.githubusercontent.com/63902542/230895751-31e1c476-35c3-4118-83c1-f71623246c8c.png)

**Comment by VlSomers** [comment]
You should download the dataset on the internet, and then place the masks downloaded on Google Drive in the "masks" folder. The final dataset folder structure should look like this:

```
Market-1501-v15.09.15
├── bounding_box_test
├── bounding_box_train
├── masks
│   └── pifpaf_maskrcnn_filtering
│       ├── bounding_box_test
│       ├── bounding_box_train
│       └── query
└── query
```
With images (.jpg) inside bounding_box_test/bounding_box_train/query on the first level and .npy with the masks inside pifpaf_maskrcnn_filtering, with the same subfolder structure

**Comment by MinhLe2512** [comment]
I think it's a problem with file extensions, apparently it detects those files as .npy files not .jpg, i modified the code and it works

![image](https://user-images.githubusercontent.com/63902542/230896779-1440d332-cf83-45d4-b32c-4be718dd33fc.png)
