### ISSUE TITLE
The code for Features for Multi Target Multi Camera Tracking and Re Identification in Awesome-ReID is missing

### ISSUE THREAD

**Issue by ximuaaa** [VlSomers/bpbreid#15]
Can you update this code? I would like to learn about it

**Comment by VlSomers** [comment]
Hi, I'm sorry but I don't understand which code you are referring to, can you elaborate please?

**Comment by ximuaaa** [comment]
https://github.com/VlSomers/bpbreid/blob/main/docs/AWESOME_REID.md
[CVPR18] Features for Multi-Target Multi-Camera Tracking and Re-Identification. [[paper](https://arxiv.org/abs/1803.10859)][[code](https://github.com/ergysr/DeepCC)]
this code is missing

**Comment by VlSomers** [comment]
Oh, this list comes from Torchreid, I think you should have a look there and check with the author: https://github.com/KaiyangZhou/deep-person-reid

**Comment by ximuaaa** [comment]
Thank you, I am a beginner in deep learning. May I ask why the training results of this model did not receive a weight file? Did I miss any details?
