### ISSUE TITLE
Occluded-REID and P-DukeMTMC-reID datasets!

### ISSUE THREAD

**Issue by matrxsoftware** [VlSomers/bpbreid#17]
Hi,

Could you please share the link for Occluded-REID and P-DukeMTMC-reID datasets because I couldn't find them?

Many thanks

Gh

**Comment by VlSomers** [comment]
Hi @matrxsoftware , I don't own these datasets so I cannot share them with you, sorry

**Comment by matrxsoftware** [comment]
I know that and I believe it's publicly used, so I asked of assistant to get it, because I emailed the owners and they didn't respond.
However, thanks for the response.
