### ISSUE TITLE
About generating human parsing labels

### ISSUE THREAD

**Issue by hh23333** [VlSomers/bpbreid#2]
Thans for releasing the code!
As decribed in the README file, the labels of human parsing were generated using the PifPaf pose estimation model and then filtered using segmentation masks from Mask-RCNN. Could you please give me some details about the operation "filter", thanks

**Comment by VlSomers** [comment]
Hi @hh23333, I'm sorry but you'll have to wait until we disclose everything related to the mask generation strategy, hopefully soon! Let me know if you need any other information about other parts of the work, I'll be glad to help. And great work on PVPM by the way! I haven't tried the OpenPose labels you propose on your repository, but the comparison with the ones from PifPaf might be interesting.
