### ISSUE TITLE
Hello, Vladimir ；How to solve this problem, thanks

### ISSUE THREAD

**Issue by y1b2h3** [VlSomers/bpbreid#20]
root@3e426b2db9fe:/home/bpbreid-main/scripts# python get_labels.py --source [ABSK]
/usr/local/lib/python3.8/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
* OpenPifPaf model ->  shufflenetv2k16
Traceback (most recent call last):
  File "get_labels.py", line 521, in <module>
    main()
  File "get_labels.py", line 511, in main
    pifpaf_model(imagery=img_paths, dataset_dir=args.source, is_overwrite=False)
  File "get_labels.py", line 212, in __call__
    assert len(imagery) > 0, "No images found in imagery."
AssertionError: No images found in imagery.

**Comment by QTanweer** [comment]
@y1b2h3 How did you resolve this error?
