### ISSUE TITLE
market  数据集

### ISSUE THREAD

**Issue by yaodepeng** [VlSomers/bpbreid#23]
你的market  数据集为什么少一张和原始比起来

**Comment by VlSomers** [comment]
Hi, which piece is missing?

**Comment by yaodepeng** [comment]
market 1501 原始和您的数据集差一张

**Comment by yaodepeng** [comment]
mask里面的bounding_box_test是19732个文件，实际里面应该是19733，bounding_box_train 和query都是一样的，少了一张

**Comment by yaodepeng** [comment]
从原始数据集bounding_box_test是19733个文件，但您少了一个代码说mask和原始数据不一样

**Comment by VlSomers** [comment]
From the official website (https://zheng-lab.cecs.anu.edu.au/Project/project_reid.html) there is 19732 images in bounding_box_test, not 19733. Here is a screenshot of the webpage :
![Screenshot 2023-08-25 at 14 23 42](https://github.com/VlSomers/bpbreid/assets/4105892/e997e21f-9e04-48e6-a788-5100b73e9db4)
If you still think there's an error, can you show which image is missing and past it here (filename + jpg)?

**Comment by yaodepeng** [comment]
🆗，I think i am wrong
