### ISSUE TITLE
Feature extraction - improving comparison

### ISSUE THREAD

**Issue by debenton** [VlSomers/bpbreid#28]
Quick question -

For the masks, is there a difference using the confidence field .npy vs the mask generated from RCNN? I am getting similar foreground similarities for images representing different people (trying both versions of the masks), where the people are facing front (the camera) and the body parts are visible...

Thanks for the great work again!

**Comment by VlSomers** [comment]
Hi @debenton , sorry but I'm not sure I understood your question, what do you mean by "I am getting similar foreground similarities for images representing different people (trying both versions of the masks), where the people are facing front (the camera) and the body parts are visible..."?

**Comment by debenton** [comment]
Hi @VlSomers - thanks for replying. Basically I meant, I tested the feature extraction with sample images each containing an identity (the people in the picture have their body parts available). I tried using confidence-field mask and from extractor - generated features. I then compared the distance between the features from different image - using the compute_distance function (euclidean, boolean visibility score with mask).

The resulting distance matrix generate distances that are not quite as discriminative as expected, as in a picture between person A vs another picture of person B, despite looking quite different and dressing different, have distance difference that is small ( in the range of 0.05-0.1).

I am new to ReID so I think my approach might not be completely correct. I do think your work is great, just perhaps I am not comparing them right or my images are very different from what was trained. I used pretrained weights hrnet32 - occuluded duke. Thanks!

**Comment by VlSomers** [comment]
Indeed this is very likely an issue related to the domain shift. I suggest you have a look at the literature about cross domain re-identification, the performances are usually quite bad, because it is difficult to train a general-purpose re-identifier... If you cannot train a new model on your target domain, I suggest you have a look at foundation models for reid, such as SOLIDER-REID: https://github.com/tinyvision/SOLIDER, or other works on cross-domain reid

**Comment by debenton** [comment]
understood and thanks for replying!
