### ISSUE TITLE
shape error

### ISSUE THREAD

**Issue by 2845764980** [VlSomers/bpbreid#30]
I follow the instruction as you say, but I can't run the code
![image](https://github.com/VlSomers/bpbreid/assets/39455680/0234850d-de4e-4b6a-b475-452294313c0d)

**Comment by TInaWangxue** [comment]
I also met this issue. The pretrained model I used is "bpbreid_occluded_duke_hrnet32_10670.pth". Actually I dont know the size of the masks which this project provided. I don't generate masks by myself.

**Comment by VlSomers** [comment]
Hi, this is an error with the new version of Albumentation, I just added a new commit to fix this, you can pull the last version. In "torchreid/data/transforms.py", I had to add the following argument to Compose(...): "is_check_shapes=False"

**Comment by VlSomers** [comment]
Please let me know if it works

**Comment by 2845764980** [comment]
![281253383-0234850d-de4e-4b6a-b475-452294313c0d](https://github.com/VlSomers/bpbreid/assets/39455680/9d8f76bd-1ed0-48f2-bdf3-47679580744f)                  I changed 'is_check_shape' to 'False' in composition.py, and it ran successfully. However, I haven't tried the new code yet.

**Comment by TInaWangxue** [comment]
> Please let me know if it works

It works! Thank you so much!

**Comment by 2845764980** [comment]
@TInaWangxue You are welcome! Are you Chinese? I'm ungraduate and very interested in person reid.

**Comment by TInaWangxue** [comment]
> @TInaWangxue You are welcome! Are you Chinese? I'm ungraduate and very interested in person reid.

Yes,  I'm a Chinese graduate student. Recently I've been looking at work relating to person re-identification. I'm so interested in your work.

**Comment by 2845764980** [comment]
@TInaWangxue I had done some research in short-term reid and Cloth Changing ReID. You can add my wechat 13982058834 and then we can have a deep communication.
