### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by namemute** [VlSomers/bpbreid#47]
Hello,I want to know the specific meaning of the data in npy under the mask folder. For example, What does each line and column represent in occluded_reid/masks/pifpaf_maskrcnn_filtering/whole_body_images/002_02.npy? 
![)D{$19OMHURQ81PC%@ILVZP](https://github.com/user-attachments/assets/25d60af8-198e-4c00-917e-fe21cd9bfb4f)

**Comment by VlSomers** [comment]
Hi @namemute, you can have a look at the function to read these masks here to have more information: https://github.com/VlSomers/bpbreid/blob/02570d5c893977685de7a547a58c0aa87fa4788c/torchreid/utils/tools.py#L124
Basically, this is an array of size H x W x N, that contains N masks of size HxW with values in between 0 and 1. These masks were generated using the pif and paf fields returned by OpenPifPaf, with N=36. You can have a look at this script to see how they are generated: https://github.com/VlSomers/bpbreid/blob/main/torchreid/scripts/get_labels.py.  You can also simply visualize these masks as heatmaps on top of their corresponding image to get a better sense of their meaning. Please also have a look at the conversation of this PR: https://github.com/VlSomers/bpbreid/pull/18

**Comment by namemute** [comment]
> Hi @namemute, you can have a look at the function to read these masks here to have more information:
> 
> https://github.com/VlSomers/bpbreid/blob/02570d5c893977685de7a547a58c0aa87fa4788c/torchreid/utils/tools.py#L124
> 
> 
> Basically, this is an array of size H x W x N, that contains N masks of size HxW with values in between 0 and 1. These masks were generated using the pif and paf fields returned by OpenPifPaf, with N=36. You can have a look at this script to see how they are generated: https://github.com/VlSomers/bpbreid/blob/main/torchreid/scripts/get_labels.py. You can also simply visualize these masks as heatmaps on top of their corresponding image to get a better sense of their meaning. Please also have a look at the conversation of this PR: #18

ok，thanks
