### ISSUE TITLE
model path

### ISSUE THREAD

**Issue by namemute** [VlSomers/bpbreid#48]
Hello author, I have finished running the model, but did not find the generated model file, will the code generate the model file? Such as "xxx.pth"
![捕获](https://github.com/user-attachments/assets/1c2a016d-5b19-439b-9b25-39950f6b5bfe)
![捕获1](https://github.com/user-attachments/assets/6aca4009-60ba-4860-8593-16e1485b2c44)

**Comment by zaibrua** [comment]
Hello, could you please tell me the configuration of your computer? There will be an error when I use 3090Ti to reproduce, I am not sure if there is a problem with my configuration

**Comment by VlSomers** [comment]
Hello @namemute, if you want to save the model ".pth" file, you should use the configuration "cfg.model.save_model_flag=True" (Have a look at all available configs inside `torchreid/scripts/default_config.py`). @zaibrua you should maybe try to use a smaller backbone or a bigger GPU.

**Comment by namemute** [comment]
> Hello, could you please tell me the configuration of your computer? There will be an error when I use 3090Ti to reproduce, I am not sure if there is a problem with my configuration

4090, but I change batch_size from 64 to 32

**Comment by namemute** [comment]
> Hello @namemute, if you want to save the model ".pth" file, you should use the configuration "cfg.model.save_model_flag=True" (Have a look at all available configs inside `torchreid/scripts/default_config.py`). @zaibrua you should maybe try to use a smaller backbone or a bigger GPU.

thanks

**Comment by zaibrua** [comment]
> > Hello, could you please tell me the configuration of your computer? There will be an error when I use 3090Ti to reproduce, I am not sure if there is a problem with my configuration
> 
> 4090, but I change batch_size from 64 to 32

Can you tell me how much memory you have?  ”occluded_reid“ works fine on a small data set, but will automatically terminate on market1501 because the system is out of memory. I use the free command on a linux system, and the configuration of my computer is as follows

![1](https://github.com/user-attachments/assets/7eef8311-160e-482e-824b-eb43a5ebcbc4)

**Comment by namemute** [comment]
> > > Hello, could you please tell me the configuration of your computer? There will be an error when I use 3090Ti to reproduce, I am not sure if there is a problem with my configuration
> > 
> > 
> > 4090, but I change batch_size from 64 to 32
> 
> Can you tell me how much memory you have? ”occluded_reid“ works fine on a small data set, but will automatically terminate on market1501 because the system is out of memory. I use the free command on a linux system, and the configuration of my computer is as follows
> 
> ![1](https://private-user-images.githubusercontent.com/139345364/398668849-7eef8311-160e-482e-824b-eb43a5ebcbc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDA1NTIsIm5iZiI6MTczNTIwMDI1MiwicGF0aCI6Ii8xMzkzNDUzNjQvMzk4NjY4ODQ5LTdlZWY4MzExLTE2MGUtNDgyZS04MjRiLWViNDNhNWViY2JjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwODA0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTFiNzI1N2EwNDkxNTA3NGE2ODAzMzMxYWZhYWJjZjI0MmM2ZTZjMTE3ZTBkYzc1Y2RkZmQ1ZjJhNjM5MjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MakFEJLqD9-M95ItVhF24JmKxPsH4tHRwtcISpMQAsk)

没在market1501数据集上跑过，看你的问题感觉可以继续调小batch_size试下，下面是我跑实验的服务器配置
![Uploading BS}HL10AMI{6X2)T[OH8GTP.png…]()

**Comment by zaibrua** [comment]
> > > > Hello, could you please tell me the configuration of your computer? There will be an error when I use 3090Ti to reproduce, I am not sure if there is a problem with my configuration
> > > 
> > > 
> > > 4090, but I change batch_size from 64 to 32
> > 
> > 
> > Can you tell me how much memory you have? ”occluded_reid“ works fine on a small data set, but will automatically terminate on market1501 because the system is out of memory. I use the free command on a linux system, and the configuration of my computer is as follows
> > ![1](https://private-user-images.githubusercontent.com/139345364/398668849-7eef8311-160e-482e-824b-eb43a5ebcbc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDA1NTIsIm5iZiI6MTczNTIwMDI1MiwicGF0aCI6Ii8xMzkzNDUzNjQvMzk4NjY4ODQ5LTdlZWY4MzExLTE2MGUtNDgyZS04MjRiLWViNDNhNWViY2JjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwODA0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTFiNzI1N2EwNDkxNTA3NGE2ODAzMzMxYWZhYWJjZjI0MmM2ZTZjMTE3ZTBkYzc1Y2RkZmQ1ZjJhNjM5MjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MakFEJLqD9-M95ItVhF24JmKxPsH4tHRwtcISpMQAsk)
> 
> 没在market1501数据集上跑过，看你的问题感觉可以继续调小batch_size试下，下面是我跑实验的服务器配置 ![Uploading BS}HL10AMI{6X2)TOH8GTP.png…

这个图片我看不到哇，你能加个微信聊聊吗？我的微信同号：15896349335

**Comment by namemute** [comment]
> Hello @namemute, if you want to save the model ".pth" file, you should use the configuration "cfg.model.save_model_flag=True" (Have a look at all available configs inside `torchreid/scripts/default_config.py`). @zaibrua you should maybe try to use a smaller backbone or a bigger GPU.

Hello author, I would like to know the specific meaning of the data in the red box in the following picture？such  0.71、0.74、0.68.......
![( G`G`U)G0BZ0Q{Z$C)`N`3](https://github.com/user-attachments/assets/a49a5a6d-df55-4087-88c1-47a1b9997f2f)

**Comment by VlSomers** [comment]
The left most box is the global distance of that gallery sample to the query, and the remaining red boxes are the local distances of each gallery body part to the corresponding body part of the query

**Comment by namemute** [comment]
> The left most box is the global distance of that gallery sample to the query, and the remaining red boxes are the local distances of each gallery body part to the corresponding body part of the query

ok，thanks
