### ISSUE TITLE
implementation of bpbreid

### ISSUE THREAD

**Issue by blessedDS** [VlSomers/bpbreid#9]
hello , i have tried the code from inference and tried to see the visualization as mentioned in the code but after following the instruction still i couldn't get the visualization ranking 
what should i do for it ?

**Comment by VlSomers** [comment]
Hi, what is the issue you have? The configuration "cfg.project.logger.save_disk = True" should be activated by default, meaning the visualization should be saved on the disk, can you check your log folder to see if there was an image created somewhere?

**Comment by blessedDS** [comment]
yes thank you so much for your quick response i have realized that in logs it saved also could you help with providing code for pifpaf mask filtering and human parsing labels
